### ISSUE TITLE
ToDo: Put all ApRES data in a zarr in the google bucket.

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/greenland-lakes#10]
Steps towards this include:

- [x] put single bursts into an xarray (https://github.com/ldeo-glaciology/phase-sensitive-radar-processing/blob/main/code/ApRES_Python_Nicholls_2021/notebooks/ApRES_to_xarray.ipynb)

- [x] put all the bursts in a single dat file into an xarray (https://github.com/ldeo-glaciology/phase-sensitive-radar-processing/blob/main/code/ApRES_Python_Nicholls_2021/notebooks/ApRES_to_xarray.ipynb)

- [x] put the dat files int he google bucket (see #8) 

- [x] work out how to load DAT files from the google bucket (this PR https://github.com/ldeo-glaciology/phase-sensitive-radar-processing/pull/5 adds this capability to ApRESDefs. I included an NB showing how to use this new capability [here](https://github.com/ldeo-glaciology/greenland-lakes/blob/main/ApRES/load_dats_from_bucket.ipynb))

- [x] work out how to do the to_xarray step in the cloud with the DAT files in the google bucket (the repo XApRES has code with this capability now, after PR https://github.com/ldeo-glaciology/XApRES/pull/4)

- [x] loop over all the dat files for a single ApRES unit and create one big xarray (the final solution was to load each dat file and put it in an xarray individually, rechunk it to length 1 in the time dimension, and write each one to an individual zarr store in the google bucket: [this NB ]( https://github.com/ldeo-glaciology/XApRES/blob/main/notebooks/to_zarr/to_individual_zarr.ipynb) does this)

- [x] write this xarray to zarr ([this NB](https://github.com/ldeo-glaciology/XApRES/blob/main/notebooks/to_zarr/write_big_zarrs.ipynb) loads all the individual zarr stores lazily, concatenates them, computes and adds the stacked profiles, rechunks in the time dimension to a larger length, and write to one large zarr store).

- [x] do this for all three units from the 2022 May-Sep period

~~[x] investigate using datatrees to combine the datasets from different ApRES units together (https://github.com/xarray-contrib/datatree)~~. I decided this is not really needed, so I will leave it for a while.

**Comment by jkingslake** [comment]
This code now lazily loads the ApRES data from any of the three sites:
```
def reload(site):
    filename = f'gs://ldeo-glaciology/apres/greenland/2022/single_zarrs/{site}'
    ds = xr.open_dataset(filename,
        engine='zarr', 
        chunks={}) 
    return ds
A101 = reload("A101')
A103 = reload("A103')
A104 = reload("A104')

```
